sonar.projectKey=hajra-mern-notes-app
sonar.projectName=Notes App
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend
sonar.tests=frontend/src,backend/test
sonar.test.inclusions=**/__tests__/**,**/*.test.js,**/*.test.jsx,backend/test/test.setup.js,backend/test/helpers/**,frontend/src/setupTests.js,frontend/src/tests/**
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**,backend/src/uploads/**,**/.nyc_output/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info